#!/bin/bash
# https://github.com/thefoster/ysay-hotkey
# Audiowiedergabe des ausgewählten Textes vorzeitig abbrechen
# Datei: ~/bin/ysaykill

if [ -s /tmp/ysay-avplay.pid ]; then
PID="$(cat /tmp/ysay-avplay.pid)";
kill -- "-$PID" 2>/dev/null;
rm -f /tmp/ysay-avplay.pid;
fi
